import { useEffect, useState } from 'react'
import api from '../services/api'

const blank = { company_name: '', company_logo: '', company_address: '', phone_number: '', email: '', website: '' }

export default function CompanySettings() {
  const [form, setForm] = useState(blank)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  useEffect(() => { api.get('/admin/company-settings').then(({ data }) => setForm(data.settings || blank)).catch(() => setError('Unable to load company settings.')) }, [])
  const save = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const { data } = await api.put('/admin/company-settings', form); setForm(data.settings); setMessage('Company settings saved.') } catch (err) { setError(err.response?.data?.message || 'Unable to save company settings.') } finally { setBusy(false) } }
  const backup = async () => { try { const response = await api.get('/admin/backup', { responseType: 'blob' }); const link = document.createElement('a'); link.href = URL.createObjectURL(response.data); link.download = 'visitor-management-backup.db'; link.click(); URL.revokeObjectURL(link.href) } catch { setError('Unable to download backup.') } }
  const restore = async (event) => { const backupFile = event.target.files?.[0]; if (!backupFile || !window.confirm('Restore this database? Current data will be replaced and you must sign in again.')) return; const body = new FormData(); body.append('backup', backupFile); setBusy(true); try { await api.post('/admin/restore', body, { headers: { 'Content-Type': 'multipart/form-data' } }); localStorage.removeItem('smart-visitor-user'); window.location.href = '/login' } catch (err) { setError(err.response?.data?.message || 'Unable to restore the backup.') } finally { setBusy(false); event.target.value = '' } }
  return <div className="space-y-6"><section className="rounded-[32px] bg-white p-6 shadow-soft dark:bg-slate-900"><h2 className="text-xl font-semibold dark:text-white">Company Settings</h2><p className="mt-1 text-sm text-textSecondary">Brand your login experience, navigation, reports, and visitor passes.</p><form onSubmit={save} className="mt-6 grid gap-4 md:grid-cols-2">{Object.entries({ company_name: 'Company name', company_logo: 'Company logo URL', company_address: 'Company address', phone_number: 'Phone number', email: 'Email', website: 'Website' }).map(([key, label]) => <label key={key} className={key === 'company_address' ? 'md:col-span-2' : ''}><span className="text-sm text-textSecondary">{label}</span><input required={key === 'company_name'} type={key === 'email' ? 'email' : key === 'website' ? 'url' : 'text'} value={form[key] || ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-2 w-full rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-800 dark:text-white" /></label>)}<button disabled={busy} className="rounded-3xl bg-primary px-6 py-3 text-sm font-semibold text-white disabled:opacity-50">Save Settings</button></form></section><section className="rounded-[32px] bg-white p-6 shadow-soft dark:bg-slate-900"><h2 className="text-xl font-semibold dark:text-white">Backup & Restore</h2><p className="mt-1 text-sm text-textSecondary">Download a SQLite backup or restore a previously downloaded database.</p><div className="mt-5 flex flex-wrap gap-3"><button onClick={backup} className="rounded-3xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white">Download Backup</button><label className="cursor-pointer rounded-3xl bg-rose-600 px-5 py-3 text-sm font-semibold text-white">Restore Backup<input onChange={restore} accept=".db,.sqlite,.sqlite3" type="file" className="hidden" /></label></div></section>{(message || error) && <div className={`rounded-3xl px-4 py-3 text-sm ${error ? 'bg-rose-50 text-rose-700' : 'bg-emerald-50 text-emerald-700'}`}>{error || message}</div>}</div>
}
