import { useEffect, useMemo, useState } from 'react'
import jsPDF from 'jspdf'
import api from '../services/api'
import { formatIndiaDate, formatIndiaDateTime } from '../utils/date'

const formatDateTime = formatIndiaDateTime
const csvEscape = (value) => `"${String(value ?? '').replace(/"/g, '""')}"`

export default function Reports() {
  const [visitors, setVisitors] = useState([])
  const [range, setRange] = useState('today')
  const [startDate, setStartDate] = useState('')
  const [endDate, setEndDate] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => { const load = async () => { setLoading(true); setError(''); try { const params = range === 'custom' ? { start_date: startDate, end_date: endDate } : { range }; const response = await api.get('/visitor/all', { params }); setVisitors(response.data.visitors || []) } catch (err) { setError(err.response?.data?.message || 'Unable to load report data.') } finally { setLoading(false) } }; if (range !== 'custom' || (startDate && endDate)) load(); else { setVisitors([]); setLoading(false) } }, [range, startDate, endDate])
  const rows = useMemo(() => visitors.map((visitor) => ({ 'Visitor ID': visitor.visitor_id, Name: visitor.visitor_name, Company: visitor.company_name || '', Mobile: visitor.mobile_number, 'Person to Meet': visitor.person_to_meet, Department: visitor.department, Purpose: visitor.purpose, 'Visit Date': formatIndiaDate(visitor.visit_date), 'Check-In Time': formatDateTime(visitor.check_in_time), 'Check-Out Time': formatDateTime(visitor.check_out_time), Duration: visitor.duration || '', Status: visitor.status })), [visitors])
  const exportExcel = () => { if (!rows.length) return; const csv = [Object.keys(rows[0]).map(csvEscape).join(','), ...rows.map((row) => Object.values(row).map(csvEscape).join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); link.download = 'visitor-history.csv'; link.click(); URL.revokeObjectURL(link.href) }
  const exportPdf = () => { if (!rows.length) return; const doc = new jsPDF({ orientation: 'landscape' }); doc.setFontSize(16); doc.text('Visitor History Report', 14, 16); doc.setFontSize(8); let y = 28; rows.forEach((row, index) => { if (y > 190) { doc.addPage(); y = 18 } doc.text(`${index + 1}. ${row.Name} | ${row['Visit Date']} | In: ${row['Check-In Time']} | Out: ${row['Check-Out Time']} | ${row.Duration || '—'} | ${row.Status}`, 14, y); y += 8 }); doc.save('visitor-history.pdf') }
  return <div className="space-y-6"><div className="rounded-[32px] bg-white p-6 shadow-soft dark:bg-slate-900"><h2 className="text-xl font-semibold text-textPrimary dark:text-white">Visitor Reports</h2><p className="mt-1 text-sm text-textSecondary">Filter visitor history and export it for record keeping.</p><div className="mt-5 grid gap-3 md:grid-cols-3"><select value={range} onChange={(e) => setRange(e.target.value)} className="rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-800 dark:text-white"><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="this_week">This Week</option><option value="this_month">This Month</option><option value="custom">Custom Date Range</option></select>{range === 'custom' && <><input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-800 dark:text-white"/><input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-800 dark:text-white"/></>}</div></div>{error && <div className="rounded-3xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}<div className="rounded-[32px] bg-white p-6 shadow-soft dark:bg-slate-900"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><p className="text-sm text-textSecondary">{loading ? 'Loading records...' : `${visitors.length} visitor record${visitors.length === 1 ? '' : 's'} found`}</p><div className="flex flex-wrap gap-3"><button disabled={!rows.length} onClick={exportExcel} className="rounded-3xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">Export Excel</button><button disabled={!rows.length} onClick={exportPdf} className="rounded-3xl bg-primary px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">Export PDF</button></div></div><div className="mt-5 overflow-x-auto"><table className="min-w-[850px] w-full text-left text-sm"><thead className="bg-slate-50 dark:bg-slate-800"><tr>{['Visitor','Visit Date','Check-In','Check-Out','Duration','Status'].map((heading) => <th key={heading} className="px-4 py-3 text-textSecondary">{heading}</th>)}</tr></thead><tbody>{visitors.map((visitor) => <tr key={visitor.id} className="border-t border-slate-100 dark:border-slate-800"><td className="px-4 py-3 dark:text-white">{visitor.visitor_name}</td><td className="px-4 py-3 dark:text-white">{visitor.visit_date}</td><td className="px-4 py-3 dark:text-white">{formatDateTime(visitor.check_in_time)}</td><td className="px-4 py-3 dark:text-white">{formatDateTime(visitor.check_out_time)}</td><td className="px-4 py-3 dark:text-white">{visitor.duration || '—'}</td><td className="px-4 py-3 dark:text-white">{visitor.status}</td></tr>)}</tbody></table></div></div></div>
}
